woadaptor:
  image: woadaptor:v5
  environment:
    - WOTASKD_HOSTS wotaskd:1085
  links:
    - wotaskd:wotaskd
  ports:
    - "80:80"
  #volumes:
  #  - /woapps/web:/usr/local/apache2/htdocs/WebObjects
wotaskd:
  image: wotaskd:v6
  ports:
    - "1085:1085"
  #volumes:
  #  - /woapps:/woapps
javamonitor:
  image: javamonitor
  ports:
    - "56789:56789"
  links:
    - wotaskd:wotaskd
